name: Lint and Test

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Chekout code
        uses: actions/checkout@v2
      - name: Use Deno
        uses: denoland/setup-deno@v1
      - run: deno fmt --check
      - run: deno check src/mod.ts
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Deno
        uses: denoland/setup-deno@v1
      - run: deno test